# Generated by Django 3.2.25 on 2024-11-01 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshareauth', '0004_operator'),
        ('User_Homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePricing',
            fields=[
                ('pricing_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'vehicle_pricing',
            },
        ),
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.AddField(
            model_name='station',
            name='station_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='station',
            table='station',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance')], default='available', max_length=50)),
                ('battery_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_Homepage.station')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('rental_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='active', max_length=50)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='eshareauth.customer')),
                ('end_station_id', models.ForeignKey(db_column='end_station_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_end_station', to='User_Homepage.station')),
                ('start_station_id', models.ForeignKey(db_column='start_station_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_start_station', to='User_Homepage.station')),
                ('vehicle_id', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='User_Homepage.vehicle')),
            ],
            options={
                'db_table': 'rental',
            },
        ),
    ]
