# Generated by Django 5.0.3 on 2024-10-29 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('captcha', models.CharField(max_length=4)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('dateofbirth', models.DateField()),
                ('customer_password', models.CharField(max_length=255)),
                ('customer_number', models.CharField(max_length=12, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(max_length=254, unique=True)),
                ('manager_password', models.CharField(max_length=255)),
                ('manager_phone', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100)),
                ('operator_email', models.EmailField(max_length=254, unique=True)),
                ('operator_password', models.CharField(max_length=255)),
                ('operator_phone', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'operator',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('station_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='VehiclePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'vehicle_pricing',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('rental_status', models.CharField(default='active', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshareauth.customer')),
                ('end_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_station', to='eshareauth.station')),
                ('start_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_station', to='eshareauth.station')),
            ],
            options={
                'db_table': 'rental',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshareauth.customer')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshareauth.rental')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_status', models.CharField(default='available', max_length=50)),
                ('battery_percentage', models.IntegerField()),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshareauth.station')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.AddField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshareauth.vehicle'),
        ),
        migrations.CreateModel(
            name='OperatorTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50)),
                ('task_completed_time', models.DateTimeField(null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshareauth.operator')),
                ('movement_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshareauth.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshareauth.vehicle')),
            ],
            options={
                'db_table': 'operator_tasks',
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.CharField(max_length=255)),
                ('bell_condition', models.BooleanField()),
                ('handle_condition', models.BooleanField()),
                ('tyre_condition', models.BooleanField()),
                ('resolved_at', models.DateTimeField(null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshareauth.operator')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshareauth.vehicle')),
            ],
            options={
                'db_table': 'vehicle_maintenance',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(max_length=50, null=True)),
                ('payment_time', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_wallet', to='eshareauth.customer')),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshareauth.rental')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshareauth.wallet')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_wallet', to='eshareauth.wallet'),
        ),
    ]
