# Generated by Django 5.0.3 on 2024-10-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshareauth', '0003_delete_captchamodel_remove_feedback_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100)),
                ('operator_email', models.EmailField(max_length=254, unique=True)),
                ('operator_password', models.CharField(max_length=255)),
                ('operator_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'operator',
            },
        ),
    ]
